/*
 * generated by Xtext 2.12.0
 */
package fr.unice.polytech.alexisc.smarthomedsl.ui;

import com.google.inject.Injector;
import fr.unice.polytech.alexisc.smarthomedsl.smarthome.ui.internal.SmarthomeActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SmartHomeExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SmarthomeActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SmarthomeActivator.getInstance().getInjector(SmarthomeActivator.FR_UNICE_POLYTECH_ALEXISC_SMARTHOMEDSL_SMARTHOME);
	}
	
}
