/*
 * generated by Xtext 2.12.0
 */
package fr.unice.polytech.alexisc.smarthomedsl.ide


/**
 * Use this class to register ide components.
 */
class SmartHomeIdeModule extends AbstractSmartHomeIdeModule {
}
