/*
 * generated by Xtext 2.12.0
 */
package fr.unice.polytech.alexisc.smarthomedsl.ui.tests;

import com.google.inject.Injector;
import fr.unice.polytech.alexisc.smarthomedsl.smarthome.ui.internal.SmarthomeActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class SmartHomeUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SmarthomeActivator.getInstance().getInjector("fr.unice.polytech.alexisc.smarthomedsl.SmartHome");
	}

}
