/**
 * generated by Xtext 2.12.0
 */
package smarthome.dsl.ide;

import smarthome.dsl.ide.AbstractDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class DslIdeModule extends AbstractDslIdeModule {
}
