/**
 * generated by Xtext 2.12.0
 */
package fr.unice.polytech.alexisc.smarthomedsl.ide;

import com.google.inject.Injector;
import fr.unice.polytech.alexisc.smarthomedsl.SmartHomeStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class SmartHomeIdeSetup extends SmartHomeStandaloneSetup {
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nType mismatch: cannot convert from SmartHomeRuntimeModule to Module");
  }
}
