/**
 * generated by Xtext 2.12.0
 */
package fr.unice.polytech.alexisc.smarthomedsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.unice.polytech.alexisc.smarthomedsl.SmartHomeRuntimeModule;
import fr.unice.polytech.alexisc.smarthomedsl.SmartHomeStandaloneSetup;
import fr.unice.polytech.alexisc.smarthomedsl.ide.SmartHomeIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class SmartHomeIdeSetup extends SmartHomeStandaloneSetup {
  @Override
  public Injector createInjector() {
    SmartHomeRuntimeModule _smartHomeRuntimeModule = new SmartHomeRuntimeModule();
    SmartHomeIdeModule _smartHomeIdeModule = new SmartHomeIdeModule();
    return Guice.createInjector(Modules2.mixin(_smartHomeRuntimeModule, _smartHomeIdeModule));
  }
}
