/**
 * generated by Xtext 2.12.0
 */
package fr.unice.polytech.alexisc.smarthomedsl.ide;

import fr.unice.polytech.alexisc.smarthomedsl.ide.AbstractSmartHomeIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class SmartHomeIdeModule extends AbstractSmartHomeIdeModule {
}
