/**
 * generated by Xtext 2.12.0
 */
package fr.unice.polytech.alexisc.smarthomedsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SmartHomeRuntimeModule /* implements AbstractSmartHomeRuntimeModule  */{
}
