/**
 * generated by Xtext 2.12.0
 */
package fr.unice.polytech.alexisc.smarthomedsl;

import fr.unice.polytech.alexisc.smarthomedsl.SmartHomeStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SmartHomeStandaloneSetup extends SmartHomeStandaloneSetupGenerated {
  public static void doSetup() {
    new SmartHomeStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
