/**
 * generated by Xtext 2.12.0
 */
package fr.unice.polytech.alexisc.smarthomedsl;

import fr.unice.polytech.alexisc.smarthomedsl.AbstractSmartHomeRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SmartHomeRuntimeModule extends AbstractSmartHomeRuntimeModule {
}
