/*
 * generated by Xtext 2.12.0
 */
package fr.unice.polytech.alexisc.smarthomedsl.ide.contentassist.antlr;

import com.google.inject.Inject;
import fr.unice.polytech.alexisc.smarthomedsl.ide.contentassist.antlr.internal.InternalSmartHomeParser;
import fr.unice.polytech.alexisc.smarthomedsl.services.SmartHomeGrammarAccess;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class SmartHomeParser extends AbstractContentAssistParser {

	@Inject
	private SmartHomeGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalSmartHomeParser createParser() {
		InternalSmartHomeParser result = new InternalSmartHomeParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getHomeAccess().getGroup(), "rule__Home__Group__0");
					put(grammarAccess.getHomeAccess().getGroup_3(), "rule__Home__Group_3__0");
					put(grammarAccess.getHomeAccess().getGroup_3_3(), "rule__Home__Group_3_3__0");
					put(grammarAccess.getSensorAccess().getGroup(), "rule__Sensor__Group__0");
					put(grammarAccess.getHomeAccess().getSensorsAssignment_3_2(), "rule__Home__SensorsAssignment_3_2");
					put(grammarAccess.getHomeAccess().getSensorsAssignment_3_3_1(), "rule__Home__SensorsAssignment_3_3_1");
					put(grammarAccess.getSensorAccess().getNameAssignment_2(), "rule__Sensor__NameAssignment_2");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public SmartHomeGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SmartHomeGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
