/**
 * generated by Xtext 2.12.0
 */
package fr.unice.polytech.alexisc.smarthomedsl.ui.contentassist;

import fr.unice.polytech.alexisc.smarthomedsl.ui.contentassist.AbstractSmartHomeProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class SmartHomeProposalProvider extends AbstractSmartHomeProposalProvider {
}
