/**
 * generated by Xtext 2.12.0
 */
package fr.unice.polytech.alexisc.smarthomedsl.scoping;

import fr.unice.polytech.alexisc.smarthomedsl.scoping.AbstractSmartHomeScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class SmartHomeScopeProvider extends AbstractSmartHomeScopeProvider {
}
